name: expense_mate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.69.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.2
  path_provider: ^2.1.4
  uuid: ^4.4.0

  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.17.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: fonts/YourFont.ttf